#!/bin/bash
# Example: Analyze recorded performance data with perf-rs report
#
# This example demonstrates how to analyze perf.data files
# generated by perf-rs record.

set -e

echo "=== perf-rs report examples ==="
echo ""

# Basic report
echo "1. Generate basic report from perf.data:"
echo "   sudo perf-rs report"
echo ""

# Specify input file
echo "2. Analyze custom data file:"
echo "   sudo perf-rs report --input my_profile.data"
echo ""

# Show top N functions
echo "3. Show top 10 most expensive functions:"
echo "   sudo perf-rs report --top 10"
echo ""

# Output as JSON
echo "4. Generate JSON output:"
echo "   sudo perf-rs report --format json"
echo ""

# Sort by different fields
echo "5. Sort by sample count:"
echo "   sudo perf-rs report --sort sample"
echo ""

# Combine options
echo "6. Top 20 functions sorted by overhead:"
echo "   sudo perf-rs report --top 20 --sort overhead"
echo ""

# Save report to file
echo "7. Save report to file:"
echo "   sudo perf-rs report --format json > report.json"
echo ""

echo "Sort options:"
echo "  overhead  - Sort by percentage overhead (default)"
echo "  sample    - Sort by sample count"
echo "  period    - Sort by period value"
echo ""
echo "Output formats:"
echo "  text  - Human-readable text (default)"
echo "  json  - JSON format for tooling integration"
echo ""
echo "Note: Requires debug symbols in binaries for symbol resolution."